blog/urls.py
from django.urls import path
from .views import listfiles, download, query_set, send_email,detailfile,upload

urlpatterns = [
    path('',listfiles,name='list'),
    path('detail/<int:pk>/',detailfile, name= 'detail'),
    path('files/download/<int:file_id>/', download, name='file_download'),
    path('results/',query_set,name='search_results'),
    path('blog/detail/<int:pk>/',send_email, name='share_mail'),
    path('blog/upload',upload,name='upload'),

]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('',include('blog.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
 

blog/models.py
from django.db import models
import os

# Create your models here.
class FilesAdmin(models.Model):
    adminupload= models.FileField(upload_to='media/')
    title = models.CharField(max_length=50)
    description = models.TextField()
    downloadcount = models.IntegerField(default=0,blank=True)
    emailcount= models.IntegerField(default=0,blank=True)
    
    def get_file_type(self):
        file_extension = os.path.splitext(self.adminupload.name)[1]
        file_type = file_extension.lower().lstrip('.')
        if file_type in ['jpg','png','gif','jpeg']:
            return 'image'
        elif file_type in ['mp4','mkv','webm']:
            return 'video'
        
        elif file_type == 'pdf':
            return 'pdf'
        elif file_type in ['mp3','wav','aac']:
            return 'audio'
        else:
            return None
        
    
    def __str__(self):
        return self.title

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}File Home{% endblock title %}</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .container2 {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
        align-items: center;
      }
    </style>
</head>
<body>
  <div class="container">
    <header class="p-3 mb-3 border-bottom bg-dark">
        <div class="container2">
          <div class="d-flex align-items-center">
            <a class="navbar-brand text-white fs-4 me-3" href="{% url 'list' %}">File Home</a>
            {% if user.is_authenticated %}
            <div class="dropdown">
              <a href="#" class="d-block link-light text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="bi bi-person-fill me-2"></i>{{ user.email }}
              </a>
              <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                <li><a class="dropdown-item" href="{% url 'logout' %}">Log Out</a></li>
              </ul>
            </div>
            {% endif %}
          </div>
          
          {% if user.is_authenticated %}
            
          <div class="d-flex flex-column flex-md-row align-items-center mt-3 mt-md-0">
            <div class="search-form mb-3 mb-md-0">
              <form method= "get" action= "{% url 'search_results' %}" class="d-flex">
                <input name="q" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              </form>
            </div>
            {% endif %}
            
            {% if user.is_authenticated and user.is_staff %}
            <div class="upload-btn">
              <a href="{% url 'upload' %}" class="btn btn-secondary btn-sm">
                <i class="bi bi-cloud-arrow-up-fill me-2"></i>Add File
              </a>
            </div>
            {% endif %}
          </div>
        </div>
    </header>
         
    <main>    
      {% if messages %}
        {% for message in messages %}
          <div class="text-center font-weight-bold alert alert-dismissible fade show
              {% if message.level_tag == 'error' %}
              alert-danger
              {% else %}
              alert-{{ message.tags }}
              {% endif %}">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
      {% endif %}
      {% block content %}
      {% endblock content %}
    </main>
  </div>
  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card mt-5">
          <div class="card-body text-center">
            <div class="file-icon-container">
              {% if file.get_file_type == 'image' %}
                <img src="{{file.adminupload.url}}" class="file-icon img-fluid" alt="{{file.title}}">
              {% elif file.get_file_type == 'video' %}
              <img src="{% static 'images/video_icon.jpg' %}" class="file-icon img-fluid" alt="{{file.title}}">
              {% elif file.get_file_type == 'audio' %}
                <img src="{% static 'images/sound_icon.jpg' %}"  alt="{{file.title}}"  >
              {% elif file.get_file_type == 'pdf' %}
                <img src="{% static 'images/pdf_icon.jpg' %}" class="file-icon img-fluid" alt="{{file.title}}">
              {% else %}
                <img src="{% static 'file_icon.jpg' %}" class="file-icon img-fluid" alt="{{file.title}}">
              {% endif %}
            </div>
            <h2 class="card-title mt-4 mb-3" style="font-size: 28px;">{{ file.title }}</h2>
            <p class="card-text">{{ file.description }}</p>
            <div class="file-actions mt-4">
              <a href="{% url 'file_download' file.pk %}" class="btn btn-primary" download>Download</a>
              <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#shareModal">Share via Email</button>
              <a class="btn btn-success mx-1" href="{{ file.adminupload.url }}" target="_blank">Preview</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Share via Email Modal -->
  <div class="modal fade" id="shareModal" tabindex="-1" role="dialog" aria-labelledby="shareModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="shareModalLabel">Share via Email</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form method="post" action="{% url 'share_mail' pk=file.pk %}">
            {% csrf_token %}
            <div class="form-group">
              <label for="recipient_email">Recipient Email</label>
              <input type="email" class="form-control" id="recipient_email" name="recipient_email" required>
            </div>
            <br>
            <button type="submit" class="btn btn-primary">Send Email</button>
          </form>
        </div>
      </div>
    </div>
  </div>

  <!-- Include the necessary JavaScript files for Bootstrap -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

  <style>
    .file-icon-container {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 200px;
    }
    .file-icon {
      max-width: 200px;
      max-height: 200px;
    }
    .file-preview {
      margin-top: 20px;
    }
    .file-preview-image {
      max-width: 100%;
      height: auto;
    }
    .file-preview-video {
      max-width: 100%;
    }
    .file-actions {
      margin-top: 20px;
    }
  </style>
{% endblock %}

templates/email_form.html
<!DOCTYPE html>
<html>
<head>
    <title>Send Email</title>
</head>
<body>
    <h1>Send Email</h1>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Send Email</button>
    </form>
</body>
</html>

templates/list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <div class="container">
    <h1 class="text-center mt-4 mb-4" style="font-size: 28px;">File Server</h1>

    <div class="row">
      <div class="col-md-12">
        <h3 class="ml-3">All Files</h3>
        
        <div class="row">
          {% for file in files %}
            <div class="col-md-4">
              <div class="card mb-4">
                <div class="card-body">
                  <div class="file-icon-container">
                    {% if file.get_file_type == 'image' %}
                      <img src="{{file.adminupload.url}}" class="file-icon img-fluid" alt="{{file.title}}">
                    {% elif file.get_file_type == 'video' %}
                    <img src="{% static 'images/video_icon.jpg' %}" class="file-icon img-fluid" alt="{{file.title}}">
                    {% elif file.get_file_type == 'audio' %}
                      <img src="{% static 'images/sound_icon.jpg' %}"  alt="{{file.title}}"  >
                    {% elif file.get_file_type == 'pdf' %}
                      <img src="{% static 'images/pdf_icon.jpg' %}" class="file-icon img-fluid" alt="{{file.title}}">
                    {% else %}
                      <img src="{% static 'file_icon.jpg' %}" class="file-icon img-fluid" alt="{{file.title}}">
                    {% endif %}
                  </div>
                  <h5 class="card-title text-center mt-3 mb-3"><a href="{% url 'detail' file.pk %}">{{ file.title }}</a></h5>
                  {% if user.is_staff %}
                  <div class="file-info">
                    <span class="file-info-item">Downloads: {{ file.downloadcount }}</span>
                    <span class="file-info-item">Emails Sent: {{ file.emailcount }}</span>
                  </div>
                  {% endif %}
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>

  <!-- Include the necessary CSS and font files for Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

  <style>
    .file-icon-container {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 200px;
    }
    .file-icon {
      max-width: 120px;
      max-height: 120px;
    }
    .card-body {
      padding-bottom: 1.25rem;
    }
    .file-info {
      margin-top: 10px;
    }
    .file-info-item {
      display: block;
      font-size: 14px;
    }
    .ml-3 {
      text-align: left;
    }
    .card-title {
      margin-top: 0.5rem;
      margin-bottom: 5px;
      font-size: 20px;
    }
  </style>
{% endblock %}

templates/preview_audio.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card mt-5">
          <div class="card-body text-center">
            <h2 class="card-title mt-4 mb-3" style="font-size: 28px;">Audio Preview</h2>
            <div class="file-preview">
              <audio src="{{ file_url }}" controls></audio>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/preview_image.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card mt-5">
          <div class="card-body text-center">
            <h2 class="card-title mt-4 mb-3" style="font-size: 28px;">Image Preview</h2>
            <div class="file-preview">
              <img src="{{ file_url }}" class="file-preview-image" alt="Image Preview">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/preview_pdf.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card mt-5">
          <div class="card-body text-center">
            <h2 class="card-title mt-4 mb-3" style="font-size: 28px;">PDF Preview</h2>
            <div class="file-preview">
              <embed src="{{ file_url }}" type="application/pdf" width="100%" height="600px">
            </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/preview_unsupported.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card mt-5">
          <div class="card-body text-center">
            <h2 class="card-title mt-4 mb-3" style="font-size: 28px;">Unsupported File Type</h2>
            <p class="text-muted">Sorry, the preview for this file type is not supported.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/preview_video.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card mt-5">
          <div class="card-body text-center">
            <h2 class="card-title mt-4 mb-3" style="font-size: 28px;">Video Preview</h2>
            <div class="file-preview">
              <video src="{{ file_url }}" class="file-preview-video" controls></video>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/search_results.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Search Results{% endblock title %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-md-12">
      <h3 class="ml-3">Search results for "{{query}}"</h3>
      <br>
      <div class="row">
        {% for file in files %}
          <div class="col-md-4">
            <div class="card mb-4">
              <div class="card-body">
                <div class="file-icon-container">
                  {% if file.get_file_type == 'image' %}
                    <img src="{{file.adminupload.url}}" class="file-icon img-fluid" alt="{{file.title}}">
                  {% elif file.get_file_type == 'video' %}
                  <img src="{% static 'images/video_icon.jpg' %}" class="file-icon img-fluid" alt="{{file.title}}">
                  {% elif file.get_file_type == 'audio' %}
                    <img src="{% static 'images/sound_icon.jpg' %}"  alt="{{file.title}}"  >
                  {% elif file.get_file_type == 'pdf' %}
                    <img src="{% static 'images/pdf_icon.jpg' %}" class="file-icon img-fluid" alt="{{file.title}}">
                  {% else %}
                    <img src="{% static 'file_icon.jpg' %}" class="file-icon img-fluid" alt="{{file.title}}">
                  {% endif %}
                </div>
                <h5 class="card-title text-center mt-3 mb-3"><a href="{% url 'detail' file.pk %}">{{ file.title }}</a></h5>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/upload.html
<!DOCTYPE html>
<html>
<head>
  <title>Upload Form</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
  <div class="container">
    <h1>Upload Form</h1>
    <form action="{% url 'upload' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
      <div class="form-group">
        <label for="id_title">Title:</label>
        <input type="text" class="form-control" name="title" maxlength="50" required id="id_title">
      </div>
      <div class="form-group">
        <label for="id_description">Description:</label>
        <textarea class="form-control" name="description" cols="40" rows="10" required id="id_description"></textarea>
      </div>
      <div class="form-group">
        <label for="id_adminupload">Adminupload:</label>
        <input type="file" class="form-control-file" name="adminupload" required id="id_adminupload">
      </div>
      <button type="submit" class="btn btn-primary">Upload</button>
    </form>
  </div>
</body>
</html>